# Generated by Django 2.2.3 on 2019-08-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
    ]
