# Generated by Django 2.2.3 on 2019-08-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_votes2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes2',
        ),
    ]
