# Generated by Django 2.2.3 on 2019-08-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choice2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice2',
        ),
    ]
